[caimp_baselines]
field.host = string
field.org_id = string
field.metric_name = string
field.avg_val = number
field.stddev_val = number
field.min_val = number
field.max_val = number
field.p5_val = number
field.p95_val = number
field.computed_at = number
