[caimp_metrics]
homePath   = $SPLUNK_DB/caimp_metrics/db
coldPath   = $SPLUNK_DB/caimp_metrics/colddb
thawedPath = $SPLUNK_DB/caimp_metrics/thaweddb
frozenTimePeriodInSecs = 604800
maxDataSize = auto_high_volume
datatype = metric

[caimp_logs]
homePath   = $SPLUNK_DB/caimp_logs/db
coldPath   = $SPLUNK_DB/caimp_logs/colddb
thawedPath = $SPLUNK_DB/caimp_logs/thaweddb
frozenTimePeriodInSecs = 7776000

[caimp_anomalies]
homePath   = $SPLUNK_DB/caimp_anomalies/db
coldPath   = $SPLUNK_DB/caimp_anomalies/colddb
thawedPath = $SPLUNK_DB/caimp_anomalies/thaweddb
frozenTimePeriodInSecs = 7776000

[caimp_ai]
homePath   = $SPLUNK_DB/caimp_ai/db
coldPath   = $SPLUNK_DB/caimp_ai/colddb
thawedPath = $SPLUNK_DB/caimp_ai/thaweddb
frozenTimePeriodInSecs = 7776000

[caimp_metrics_5m]
homePath   = $SPLUNK_DB/caimp_metrics_5m/db
coldPath   = $SPLUNK_DB/caimp_metrics_5m/colddb
thawedPath = $SPLUNK_DB/caimp_metrics_5m/thaweddb
frozenTimePeriodInSecs = 7776000

[caimp_metrics_1h]
homePath   = $SPLUNK_DB/caimp_metrics_1h/db
coldPath   = $SPLUNK_DB/caimp_metrics_1h/colddb
thawedPath = $SPLUNK_DB/caimp_metrics_1h/thaweddb
frozenTimePeriodInSecs = 31536000

[caimp_metrics_1d]
homePath   = $SPLUNK_DB/caimp_metrics_1d/db
coldPath   = $SPLUNK_DB/caimp_metrics_1d/colddb
thawedPath = $SPLUNK_DB/caimp_metrics_1d/thaweddb
frozenTimePeriodInSecs = 94608000
